version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./src:/usr/src/app/src
    restart: unless-stopped
    networks:
      - blog-network
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: blog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-blog}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - blog-network

volumes:
  postgres-data:

networks:
  blog-network:
    driver: bridge